[package]
name = "registrar"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "registrar"
path = "src/lib.rs"

[dependencies]
alloy = { version = "0.11", features = ["full"] }
eyre = "0.6.12"
tokio = "1.42.0"
dotenvy = "0.15.7"
mockall = "0.11.3"
serde_json = "1.0"
