[package]
name = "forge-examples"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]


[[example]]
name = "lengthy-post"
path = "twitter/lenghty_post.rs"

[[example]]
name = "image-post"
path = "instagram/image_post.rs"
