version: "3.7"
x-othentic-cli: &othentic-cli
  env_file:
    - .env
  image: ./dockerfile
services:
  validation-service:
    image: ghcr.io/0xzerolabs/the-forge/validation:latest
    ports:
      - "2078:2078"
    networks:
      p2p:
        ipv4_address: 10.8.0.42
  attester:
    <<: *othentic-cli
    command:
      [
        "node",
        "attester",
        "/ip4/10.8.0.69/tcp/9876/p2p/${OTHENTIC_BOOTSTRAP_ID}",
        "--avs-webapi",
        "http://10.8.0.42",
        "--l1-chain",
        "holesky",
        "--l2-chain",
        "aeneid",
      ]
    environment:
      - TASK_PERFORMER=0x0000000000000000000000000000000000000000
    networks:
      p2p:
        ipv4_address: 10.8.0.2

networks:
  p2p:
    driver: bridge
    ipam:
      config:
        - subnet: 10.8.0.0/16
          gateway: 10.8.0.1
