name: CI/Execution Tests

on:
  pull_request:
    branches: [main]
    paths:
      - "execution/**"

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: blacksmith-4vcpu-ubuntu-2204
    defaults:
      run:
        working-directory: execution

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('*/**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev pkg-config

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
