name: CI/Execution Docker Image to GHCR

on:
  release:
    types:
      - released
      - prereleased

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: build and push the image
        working-directory: ./execution
        run: |
          docker login --username hey-ewan --password ${{ secrets.GITHUB_TOKEN }} ghcr.io
          docker build . --tag ghcr.io/0xzerolabs/the-forge/execution:latest
          docker push ghcr.io/0xzerolabs/the-forge/execution:latest
